# Generated by Django 4.2 on 2023-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='longtoshort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(default=0)),
                ('custom_name', models.CharField(max_length=20, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('vist_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'custom_name',
            },
        ),
    ]
