# Generated by Django 4.2 on 2023-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtoshort',
            options={},
        ),
        migrations.AlterField(
            model_name='longtoshort',
            name='custom_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='longtoshort',
            name='long_url',
            field=models.URLField(),
        ),
    ]
